### PR TITLE
Add transition feature for PR merge and link

### PR DESCRIPTION
**Pull request by sidpremkumar**
Add a transition feature to PR when it is linked and when it is merged to custom transition.

### CODE REVIEW

**Comment by sidpremkumar** [comment]
Relates to JIRA: DEVOPSA-6974

**Comment by sidpremkumar** [comment]
Relates to JIRA: DEVOPSA-6616

**Comment by dgregor** [comment]
@sidpremkumar - would this change cover the case where the PR has a reference to the upstream issue, or would it have to include a reference to the downstream issue?

Example of a PR with reference to upstream issue: https://pagure.io/koji/pull-request/1920

**Comment by sidpremkumar** [comment]
@dgregor no it would not. This PR is not related to the PR feature, it is just related to the feature you requested that automatically transitions issues when they are linked/merged. If you want to add that feature you can submit an issue and I can work on it as soon as I get back :).

**Comment by sidpremkumar** [comment]
@ralphbean bump

**Pull request merged**
